// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqfwxunwkdjxuwgtohml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxZnd4dW53a2RqeHV3Z3RvaG1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDY0OTAsImV4cCI6MjA2MjQyMjQ5MH0.zcmmRFhYBYxMpJrlCN9gnQjdhryZsQ7vBAuPgGVhaBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);